### ISSUE TITLE
pic18f

### ISSUE THREAD

**Issue by g7wbd** [dsoze1138/MPLABXv540_pic-as_examples#1]
I failed to get the 18f examples to compile with mplab5.5.  is it me or Mchip ?

**Comment by dsoze1138** [comment]
Did a test build of these projects with MPLABX v5.50:

18F2550_isqrt_v540.X
18F4520_Compiled_Stack_Example.X
18F45K80_Example_Branch_Table.X
18F46K40_C_calling_pic-as_Example.X
18F46K42_IVT_Example.X
18F47K42_Basic_Example.X
18F47K42_Interrupts_and_Bits_Example.X
18F47K42_Interrupts_and_Bits_IVT_Example.X
18F47Q10_Example_DM164136_v545.X
18F47Q43_Example_IVT_v545.X


This project asserts syntax errors for symbols no longer defined in MPLABX v5.50 include files:

18F47K42_Interrupts_and_Bits_Example.X/test.S

Now all PIF18F project build clean.

Other issues could be in your MPLABX v5.50 installation.
